config/routes.rb
Rails.application.routes.draw do

  resources(:topics, {only: [:index, :create, :show, :edit, :update, :destroy]})  do
    resources :comments
    resources :tags
    resources :tagations
    resources :scores, {only: :create}
  end

  resources :comments do
    resources :tags, {only: [:new, :create]}
    resources :tagations, {only: [:new, :create]}
    resources :comment_scores, {only: :create}
    resources :comments, {only: [:new, :create]}
  end

  resources :tags do
    resources :tagations, {only: :create}
  end

  resources :users, only: [:show, :edit, :update, :destroy]

  get "profile" => 'users#show'
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: "topics#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  default_scope {{:order => 'created_at DESC'}}

	validates_presence_of :title
	validates_presence_of :body
	

  has_many :comments, :as => :commentable
  has_many :tagations, :as => :tagable
  has_many :tags, :through => :tagations
  belongs_to :user
  has_many :scores


  def self.search(search)
  	if search
    	where("title LIKE ? OR body LIKE ?", "%#{search}%","%#{search}%")
  	else
    	all
  	end
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  

  def index
    # @topics = Topic.order(created_at: :desc)
    @topics = Topic.search(params[:search])
    @topic = Topic.new
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def show
    if session[:user_id]
      @topic = Topic.find(params[:id])
      @user = User.find(session[:user_id])
      @taglist = get_tags(@topic)
    else
      @topics = Topic.order(created_at: :desc)
      @topic = Topic.new
      flash.now[:notice] = "You need to be logged in!"
      render 'index'
    end
  end

  def create
    if session[:user_id]
      @topic = Topic.new(topic_params)
      @topic.user_id = User.find(session[:user_id]).id
      if @topic.save
          redirect_to @topic
        else
          flash.now[:notice] = "You need to be logged in!"
          redirect_to root_path
      end
    else
      @topics = Topic.all
      @topic = Topic.new
      flash.now[:notice] = "You need to be logged in!"
      render 'index'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic=Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private
    def topic_params
      params.require(:topic).permit(:title, :body)
    end

    def get_tags(tagable)
      tags = tagable.tags.dup
      tagable.comments.each do |comment|
        tags += comment.tags
        tags += get_tags(comment)
      end
      tags.uniq
    end
  
end

app/helpers/topic_helper.rb
module TopicHelper


end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if @topic.errors.any? %>
  <div id="error_explanation">
    <h2> <%= pluralize(@topic.errors.count, "error") %>prohibited this topic from being saved: </h2>
    <ul>
      <%= @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>

  <% end %>

app/views/topics/_search.html.erb
<%= form_tag topics_path, :method => "get" do %>

  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search"%>

<% end %>

app/views/topics/edit.html.erb
<h1>Editing an topic</h1>
<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="container">
	<div class="left">

		<h4>Popular |</h4> <h4> Controversial |</h4><h4> Recent </h4>

		<% @topics.each do |topic| %>
 			 <ul>

   				 <div class="topic"><li><%= link_to "#{topic.title}", topic %></li><br>
   				 	<li>posted by: <%= topic.user.username %></li><br>
   				 	<% if @user %>
   				 	<%=link_to image_tag("http://icons.iconarchive.com/icons/rokey/the-blacy/128/black-heart-icon.png", width: 30), {controller: "scores", action: "create", topic_id: topic.id, score: {topic_id: topic.id, user_id: @user.id}}, method: 'post'%>
   				 	<% end %>
   				  </br>
   				 	 <%=topic.scores.count%> &#x2764;'s


 			<div class="tags">
				<% taglist = topic.tags.dup %>
				<% topic.comments.each do |comment| %>
				  <% taglist += comment.tags %>
				<% end %>
				<br><hr><br>
				<ul class="taglist">
				  <li class="tag">Tags: </li>
				  <% taglist.uniq.each do |tag| %>
				  <% unless tag.id == nil %>
				   <li class ="tag"> <%= link_to tag.subject, tag %> </li>
				  <% end %>
		  	 <% end %>
        </ul>
 			</div>

 </div>
 			</ul>
		<% end %>
		<div class="pagination"></div>
	</div>
	<div class="right">
		<br>
		<div class="topic">
			<h1>Have a question? Create a topic.</h1><br>
			<%= form_for @topic do |f| %>
				<p>
	  			<%= f.label :title %><br>
	  			<%= f.text_field :title %>
				</p>
				<p>
	  			<%= f.label :body %><br>
	  			<%= f.text_area :body %>
				</p>
				<p>
	  			<%= f.submit %>
				</p>
			<% end %>
		</div>
	</div>
	<div class="logo"><img src="/images/logo.png" alt="Med-Flow" /><br><br><br>
	© 2014 buffy inc. All rights reserved. Please click <a href="">here</a> for more medical information.<br><br>
	</div>
</div>

app/views/topics/show.html.erb
<div class="topicShow">
<h1><%= @topic.title %></h1>
<span class="posted">posted by: <%= @topic.user.username %></span>
<br>
<p class="topicBody"><%= @topic.body %></p>
<br>
  <div class="action_bar">
    <ul class="actionlist">
      <li class="action"><%= render "tagations/form" %></li>
      <li class="action"><%= render "tags/form" %></li>
      <% if @user %>
      <li class="action">
        <%=link_to image_tag("http://icons.iconarchive.com/icons/rokey/the-blacy/128/black-heart-icon.png", width: 30), {controller: "scores", action: "create", topic_id: @topic.id, score: {topic_id: @topic.id, user_id: @user.id}}, method: 'post'%>
      </li>
      <% end %>
      <li class="action"><%=@topic.scores.count%> &#x2764;'s</li>
      <% if @user == @topic.user %>
      <li class="action"><%= link_to 'Edit', edit_topic_path(@topic) %></li>
      <li class="action"><%= link_to "Delete", topic_path(@topic), method: :delete,
                                            data: { confirm: 'Are you sure?' }%> </li>
      <% end %>
    </ul>
  </div>

  <div class="action_bar">
    <ul class="actionlist">
      <li class="action"><%= render "comments/form" %></li>
    </ul>
  </div>
</div>

<% @topic.comments.each do |comment| %>
  <% if comment.id %>
    <%= render partial: "comments/comment", locals: { comment: comment } %>
  <% end %>
<% end %>

<br><hr><br>
  <ul class="taglist">
    <li class="tag">Tags: </li>
    <% @taglist.each do |tag| %>
      <li class ="tag"> <%= link_to tag.subject, tag %> </li>
    <% end %>
  </ul>