config/routes.rb
Rails.application.routes.draw do

  resources(:topics, {only: [:index, :create, :show, :edit, :update, :destroy]})  do
    resources :comments
    resources :tags
    resources :tagations
    resources :scores, {only: :create}
  end

  resources :comments do
    resources :tags, {only: [:new, :create]}
    resources :tagations, {only: [:new, :create]}
    resources :comment_scores, {only: :create}
    resources :comments, {only: [:new, :create]}
  end

  resources :tags do
    resources :tagations, {only: :create}
  end

  resources :users, only: [:show, :edit, :update, :destroy]

  get "profile" => 'users#show'
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: "topics#index"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tagations
  has_many :topics, :through => :tagations, :source => :tagable, :source_type => "Topic"
  has_many :comments, :through => :tagations, :source => :tagable, :source_type => "Comment"
  has_many :users, :through => :tagations

  validates :subject, presence: true 


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.find_or_create_by(tag_params)

    if params[:topic_id]
      tagable = Topic.find(params[:topic_id])
      @topic = tagable
      tagable_type = "Topic"
    else
      tagable = Comment.find(params[:comment_id])
      @topic = Topic.find(tagable.topic.id)
      tagable_type = "Comment"
    end
    
    user = User.find(session[:user_id])

    Tagation.create(tagable_id: tagable.id, tagable_type: tagable_type, user_id: user.id, tag_id: @tag.id)
    
    redirect_to @topic
  end

  def update
      if @tag.update(tag_params)
        redirect_to @tag, notice: 'Tag was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    def tag_params
      params.require(:tag).permit(:subject)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_comment_form.html.erb
<%= form_for([comment, comment.tags.build]) do |f| %>

  <div class="action">
    <%= f.text_field :subject, size: "20" %>
    <%= f.submit 'tag this', class: "tagButton" %>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= form_for([@topic, @topic.tags.build]) do |f| %>

  <div class="action">
    <%= f.text_field :subject, size: "20" %>
    <%= f.submit 'tag this', class: "smallButton" %>
  </div>

  <% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="container">
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.subject %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h2><%= @tag.subject %></h2>
<br><br>
<p>Tagged Topics</p>
<br><br>
<ul>
  <% @tag.topics.each do |topic| %>
  <li><%= link_to topic.title, topics_path(topic) %></li>
  <% end %>
</ul>

<br><br><hr><br>

<p>Tagged Comments</p>
<br><br>
<ul>
  <% @tag.comments.each do |comment| %>
  <li><%= link_to comment.body, topic_comment_path(comment.topic, comment) %></li>
  <% end %>
</ul>



<br><br><hr><br>
<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>
</div>