config/routes.rb
Rails.application.routes.draw do

  resources(:topics, {only: [:index, :create, :show, :edit, :update, :destroy]})  do
    resources :comments
    resources :tags
    resources :tagations
    resources :scores, {only: :create}
  end

  resources :comments do
    resources :tags, {only: [:new, :create]}
    resources :tagations, {only: [:new, :create]}
    resources :comment_scores, {only: :create}
    resources :comments, {only: [:new, :create]}
  end

  resources :tags do
    resources :tagations, {only: :create}
  end

  resources :users, only: [:show, :edit, :update, :destroy]

  get "profile" => 'users#show'
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: "topics#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PreventiveMeasures</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300|Inconsolata' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <img src="/images/logo.png" alt="Med-Flow" class="navlogo" />
    <h1>Med-Flow</h1>
    <ul>
      <li><i class="fa fa-user-md"></i><%= link_to 'Home', topics_path %></li>
      <% if session[:user_id] %><li><i class="fa fa-wheelchair"></i><%= link_to 'Profile', profile_path %></li><% end %>
      <li><i class="fa fa-plus-square"></i><%= link_to 'Tags', tags_path %></li>
      <% if session[:user_id] %>
      <li> <i class="fa fa-ambulance"></i><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
      <li><i class="fa fa-stethoscope"></i><%= link_to 'Login', login_path %></li>
      <li><i class="fa fa-stethoscope"></i> <%= link_to 'Signup', signup_path %></li>
      <% end %>
      <li> <%= render 'topics/search' %> </li>
    </ul>
  <% if session[:user_id] %>
  <% @user = User.find(session[:user_id]) %>
    <div class="hello"><h3>Hello <%= @user.username %>!</h3></div>
   <% end %>
  </nav>


<p><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>